// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';


function condominoToJson(condomino) {
  switch (condomino) {
    case 0 : 
        return "Michela";
    case 1 : 
        return "Gerardo";
    case 2 : 
        return "Elena";
    case 3 : 
        return "Giulia";
    
  }
}

function movimentoToJson(param) {
  var data = param[0];
  var operazione = param[1];
  var match;
  if (typeof operazione === "number") {
    match = /* tuple */[
      "PagamentoScale",
      "",
      "",
      -1
    ];
  } else {
    switch (operazione.tag | 0) {
      case 0 : 
          match = /* tuple */[
            "VersamentoQuote",
            condominoToJson(operazione[0]),
            "",
            operazione[1]
          ];
          break;
      case 1 : 
          match = /* tuple */[
            "AltraSpesa",
            "",
            operazione[0],
            operazione[1]
          ];
          break;
      case 2 : 
          match = /* tuple */[
            "AltroVersamento",
            "",
            operazione[0],
            operazione[1]
          ];
          break;
      case 3 : 
          match = /* tuple */[
            "Prestito",
            "",
            "",
            operazione[0]
          ];
          break;
      case 4 : 
          match = /* tuple */[
            "Restituzione",
            "",
            "",
            operazione[0]
          ];
          break;
      
    }
  }
  return "\n        [\n            {\n                \"y\": " + (String(data[0]) + (",\n                \"m\": " + (String(data[1]) + (",\n                \"d\": " + (String(data[2]) + ("\n            },\n            {\n                \"opType\": \"" + (String(match[0]) + ("\",\n                \"condomino\": \"" + (String(match[1]) + ("\",\n                \"causale\": \"" + (String(match[2]) + ("\",\n                \"importo\": " + (String(match[3]) + "\n            }\n        ]\n    ")))))))))))));
}

exports.condominoToJson = condominoToJson;
exports.movimentoToJson = movimentoToJson;
/* No side effect */
