// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Css = require("bs-css/src/Css.js");
var React = require("react");
var Belt_Array = require("bs-platform/lib/js/belt_Array.js");
var Link$Scale = require("../router/Link.bs.js");
var DataPureReason$Scale = require("./DataPureReason.bs.js");

var customers = /* array */[
  /* record */[
    /* id */1,
    /* name */"Christina Langworth",
    /* address : record */[
      /* street */"81 Casey Stravenue",
      /* city */"Beattyview",
      /* state */"TX",
      /* zip */"57918"
    ],
    /* phone */"877-549-1362",
    /* email */"Christina.Langworth@gmail.com"
  ],
  /* record */[
    /* id */2,
    /* name */"Victor Tillman",
    /* address : record */[
      /* street */"2811 Toby Gardens",
      /* city */"West Enrique",
      /* state */"NV",
      /* zip */"40465"
    ],
    /* phone */"(502) 091-2292",
    /* email */"Victor.Tillman30@gmail.com"
  ],
  /* record */[
    /* id */3,
    /* name */"Annabell Pouros",
    /* address : record */[
      /* street */"1550 Hodkiewicz Squares",
      /* city */"New Mireyaland",
      /* state */"CA",
      /* zip */"10212"
    ],
    /* phone */"(495) 084-7687",
    /* email */"Annabell.Pouros@yahoo.com"
  ],
  /* record */[
    /* id */4,
    /* name */"Laurence Skiles",
    /* address : record */[
      /* street */"4131 Alena Light",
      /* city */"Lake Ashtynmouth",
      /* state */"ND",
      /* zip */"68071"
    ],
    /* phone */"(687) 543-0380",
    /* email */"Laurence6@yahoo.com"
  ],
  /* record */[
    /* id */5,
    /* name */"Retta Terry",
    /* address : record */[
      /* street */"409 Frida Heights",
      /* city */"South Pearl",
      /* state */"NH",
      /* zip */"04200"
    ],
    /* phone */"(710) 751-3763",
    /* email */"Retta_Terry@gmail.com"
  ]
];

var customers1 = DataPureReason$Scale.parse(localStorage.getItem("customers"));

var list = Css.style(/* :: */[
      Css.listStyleType(Css.none),
      /* :: */[
        Css.padding(Css.zero),
        /* :: */[
          Css.margin2(Css.px(50), Css.auto),
          /* :: */[
            Css.width(Css.px(700)),
            /* :: */[
              Css.selector("li", /* :: */[
                    Css.backgroundColor(Css.rgba(150, 123, 182, 0.1)),
                    /* :: */[
                      Css.margin2(Css.px(15), Css.zero),
                      /* :: */[
                        Css.selector("a", /* :: */[
                              Css.display(Css.flexBox),
                              /* :: */[
                                Css.flexWrap(Css.wrap),
                                /* :: */[
                                  Css.textDecoration(Css.none),
                                  /* :: */[
                                    Css.padding(Css.px(20)),
                                    /* :: */[
                                      Css.selector("p", /* :: */[
                                            Css.flex(/* `num */[
                                                  5496390,
                                                  1
                                                ]),
                                            /* :: */[
                                              Css.flexBasis(Css.pct(50)),
                                              /* :: */[
                                                Css.margin(Css.zero),
                                                /* :: */[
                                                  Css.color(Css.black),
                                                  /* [] */0
                                                ]
                                              ]
                                            ]
                                          ]),
                                      /* [] */0
                                    ]
                                  ]
                                ]
                              ]
                            ]),
                        /* [] */0
                      ]
                    ]
                  ]),
              /* [] */0
            ]
          ]
        ]
      ]
    ]);

var Styles = /* module */[/* list */list];

function CustomerList(Props) {
  var cs = Belt_Array.map(customers1, (function (customer) {
          return React.createElement("li", {
                      key: String(customer[/* id */0])
                    }, React.createElement(Link$Scale.make, {
                          href: "/customers/" + String(customer[/* id */0]),
                          children: null
                        }, React.createElement("p", undefined, customer[/* name */1]), React.createElement("p", undefined, customer[/* address */2][/* street */0]), React.createElement("p", undefined, customer[/* phone */3]), React.createElement("p", undefined, customer[/* email */4])));
        }));
  return React.createElement("div", undefined, React.createElement("ul", {
                  className: list
                }, cs));
}

var make = CustomerList;

exports.customers = customers;
exports.customers1 = customers1;
exports.Styles = Styles;
exports.make = make;
/* customers1 Not a pure module */
