// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReasonReactRouter = require("reason-react/src/ReasonReactRouter.js");

function Link(Props) {
  var href = Props.href;
  var match = Props.className;
  var className = match !== undefined ? match : "";
  var children = Props.children;
  return React.createElement("a", {
              className: className,
              href: href,
              onClick: (function ($$event) {
                  $$event.preventDefault();
                  return ReasonReactRouter.push(href);
                })
            }, children);
}

var make = Link;

exports.make = make;
/* react Not a pure module */
